const standard: type = @import("std");

// Hypertext Transfer Protocol Status Code Definition
pub const HTTPStatusCode: type = []const u8;

// Hypertext Transfer Protocol Status Text Definition
pub const HTTPStatusText: type = []const u8;

// Hypertext Transfer Protocol Status Codes
pub const HTTP_ONE_HUNDRED: [3]HTTPStatusCode = "100";
pub const HTTP_ONE_HUNDRED_ONE: [3]HTTPStatusCode = "101";
pub const HTTP_ONE_HUNDRED_TWO: [3]HTTPStatusCode = "102";
pub const HTTP_ONE_HUNDRED_THREE: [3]HTTPStatusCode = "103";
pub const HTTP_TWO_HUNDRED: [3]HTTPStatusCode = "200";
pub const HTTP_TWO_HUNDRED_ONE: [3]HTTPStatusCode = "201";
pub const HTTP_TWO_HUNDRED_TWO: [3]HTTPStatusCode = "202";
pub const HTTP_TWO_HUNDRED_THREE: [3]HTTPStatusCode = "203";
pub const HTTP_TWO_HUNDRED_FOUR: [3]HTTPStatusCode = "204";
pub const HTTP_TWO_HUNDRED_FIVE: [3]HTTPStatusCode = "205";
pub const HTTP_TWO_HUNDRED_SIX: [3]HTTPStatusCode = "206";
pub const HTTP_TWO_HUNDRED_SEVEN: [3]HTTPStatusCode = "207";
pub const HTTP_TWO_HUNDRED_EIGHT: [3]HTTPStatusCode = "208";
pub const HTTP_TWO_HUNDRED_TWENTY_SIX: [3]HTTPStatusCode = "226";
pub const HTTP_THREE_HUNDRED: [3]HTTPStatusCode = "300";
pub const HTTP_THREE_HUNDRED_ONE: [3]HTTPStatusCode = "301";
pub const HTTP_THREE_HUNDRED_TWO: [3]HTTPStatusCode = "302";
pub const HTTP_THREE_HUNDRED_THREE: [3]HTTPStatusCode = "303";
pub const HTTP_THREE_HUNDRED_FOUR: [3]HTTPStatusCode = "304";
pub const HTTP_THREE_HUNDRED_SEVEN: [3]HTTPStatusCode = "307";
pub const HTTP_THREE_HUNDRED_EIGHT: [3]HTTPStatusCode = "308";
pub const HTTP_FOUR_HUNDRED: [3]HTTPStatusCode = "400";
pub const HTTP_FOUR_HUNDRED_ONE: [3]HTTPStatusCode = "401";
pub const HTTP_FOUR_HUNDRED_TWO: [3]HTTPStatusCode = "402";
pub const HTTP_FOUR_HUNDRED_THREE: [3]HTTPStatusCode = "403";
pub const HTTP_FOUR_HUNDRED_FOUR: [3]HTTPStatusCode = "404";
pub const HTTP_FOUR_HUNDRED_FIVE: [3]HTTPStatusCode = "405";
pub const HTTP_FOUR_HUNDRED_SIX: [3]HTTPStatusCode = "406";
pub const HTTP_FOUR_HUNDRED_SEVEN: [3]HTTPStatusCode = "407";
pub const HTTP_FOUR_HUNDRED_EIGHT: [3]HTTPStatusCode = "408";
pub const HTTP_FOUR_HUNDRED_NINE: [3]HTTPStatusCode = "409";
pub const HTTP_FOUR_HUNDRED_TEN: [3]HTTPStatusCode = "410";
pub const HTTP_FOUR_HUNDRED_ELEVEN: [3]HTTPStatusCode = "411";
pub const HTTP_FOUR_HUNDRED_TWELVE: [3]HTTPStatusCode = "412";
pub const HTTP_FOUR_HUNDRED_THIRTEEN: [3]HTTPStatusCode = "413";
pub const HTTP_FOUR_HUNDRED_FOURTEEN: [3]HTTPStatusCode = "414";
pub const HTTP_FOUR_HUNDRED_FIFTEEN: [3]HTTPStatusCode = "415";
pub const HTTP_FOUR_HUNDRED_SIXTEEN: [3]HTTPStatusCode = "416";
pub const HTTP_FOUR_HUNDRED_SEVENTEEN: [3]HTTPStatusCode = "417";
pub const HTTP_FOUR_HUNDRED_EIGHTEEN: [3]HTTPStatusCode = "418";
pub const HTTP_FOUR_HUNDRED_TWENTY_ONE: [3]HTTPStatusCode = "421";
pub const HTTP_FOUR_HUNDRED_TWENTY_TWO: [3]HTTPStatusCode = "422";
pub const HTTP_FOUR_HUNDRED_TWENTY_THREE: [3]HTTPStatusCode = "423";
pub const HTTP_FOUR_HUNDRED_TWENTY_FOUR: [3]HTTPStatusCode = "424";
pub const HTTP_FOUR_HUNDRED_TWENTY_FIVE: [3]HTTPStatusCode = "425";
pub const HTTP_FOUR_HUNDRED_TWENTY_SIX: [3]HTTPStatusCode = "426";
pub const HTTP_FOUR_HUNDRED_TWENTY_EIGHT: [3]HTTPStatusCode = "428";
pub const HTTP_FOUR_HUNDRED_TWENTY_NINE: [3]HTTPStatusCode = "429";
pub const HTTP_FOUR_HUNDRED_THIRTY_ONE: [3]HTTPStatusCode = "431";
pub const HTTP_FOUR_HUNDRED_FIFTEY_ONE: [3]HTTPStatusCode = "451";
pub const HTTP_FIVE_HUNDRED: [3]HTTPStatusCode = "500";
pub const HTTP_FIVE_HUNDRED_ONE: [3]HTTPStatusCode = "501";
pub const HTTP_FIVE_HUNDRED_TWO: [3]HTTPStatusCode = "502";
pub const HTTP_FIVE_HUNDRED_THREE: [3]HTTPStatusCode = "503";
pub const HTTP_FIVE_HUNDRED_FOUR: [3]HTTPStatusCode = "504";
pub const HTTP_FIVE_HUNDRED_FIVE: [3]HTTPStatusCode = "505";
pub const HTTP_FIVE_HUNDRED_SIX: [3]HTTPStatusCode = "506";
pub const HTTP_FIVE_HUNDRED_SEVEN: [3]HTTPStatusCode = "507";
pub const HTTP_FIVE_HUNDRED_EIGHT: [3]HTTPStatusCode = "508";
pub const HTTP_FIVE_HUNDRED_TEN: [3]HTTPStatusCode = "510";
pub const HTTP_FIVE_HUNDRED_ELEVEN: [3]HTTPStatusCode = "511";

// Hypertext Transfer Protocol Status Texts
pub const HTTP_CONTINUE: [8]HTTPStatusText = "Continue";
pub const HTTP_SWITCHING_PROTOCOLS: [19]HTTPStatusText = "Switching Protocols";
pub const HTTP_PROCESSING: [10]HTTPStatusText = "Processing";
pub const HTTP_EARLY_HINTS: [11]HTTPStatusText = "Early Hints";
pub const HTTP_OK: [2]HTTPStatusText = "OK";
pub const HTTP_CREATED: [7]HTTPStatusText = "Created";
pub const HTTP_ACCEPTED: [8]HTTPStatusText = "Accepted";
pub const HTTP_NON_AUTHORITATIVE_INFORMATION: [29]HTTPStatusText = "Non-Authoritative Information";
pub const HTTP_NO_CONTENT: [10]HTTPStatusText = "No Content";
pub const HTTP_RESET_CONTENT: [13]HTTPStatusText = "Reset Content";
pub const HTTP_PARTIAL_CONTENT: [15]HTTPStatusText = "Partial Content";
pub const HTTP_MULTI_STATUS: [12]HTTPStatusText = "Multi-Status";
pub const HTTP_ALREADY_REPORTED: [16]HTTPStatusText = "Already Reported";
pub const HTTP_IM_USED: [7]HTTPStatusText = "IM Used";
pub const HTTP_MULTIPLE_CHOICES: [16]HTTPStatusText = "Multiple Choices";
pub const HTTP_MOVED_PERMANENTLY: [17]HTTPStatusText = "Moved Permanently";
pub const HTTP_FOUND: [5]HTTPStatusText = "Found";
pub const HTTP_SEE_OTHER: [9]HTTPStatusText = "See Other";
pub const HTTP_NOT_MODIFIED: [12]HTTPStatusText = "Not Modified";
pub const HTTP_TEMPORARY_REDIRECT: [18]HTTPStatusText = "Temporary Redirect";
pub const HTTP_PREMANENT_REDIRECT: [18]HTTPStatusText = "Permanent Redirect";
pub const HTTP_BAD_REQUEST: [11]HTTPStatusText = "Bad Request";
pub const HTTP_UNAUTHORIZED: [12]HTTPStatusText = "Unauthorized";
pub const HTTP_PAYMENT_REQUIRED: [16]HTTPStatusText = "Payment Required";
pub const HTTP_FORBIDDEN: [9]HTTPStatusText = "Forbidden";
pub const HTTP_NOT_FOUND: [9]HTTPStatusText = "Not Found";
pub const HTTP_METHOD_NOT_ALLOWED: [18]HTTPStatusText = "Method Not Allowed";
pub const HTTP_NOT_ACCEPTABLE: [14]HTTPStatusText = "Not Acceptable";
pub const HTTP_PROXY_AUTHENTICATION_REQUIRED: [28]HTTPStatusText = "Proxy Authentication Required";
pub const HTTP_REQUEST_TIMEOUT: [15]HTTPStatusText = "Request Timeout";
pub const HTTP_CONFLICT: [8]HTTPStatusText = "Conflict";
pub const HTTP_GONE: [4]HTTPStatusText = "Gone";
pub const HTTP_LENGTH_REQUIRED: [14]HTTPStatusText = "Length Required";
pub const HTTP_PRECONDITION_FAILED: [19]HTTPStatusText = "Precondition Failed";
pub const HTTP_CONTENT_TOO_LARGE: [17]HTTPStatusText = "Content Too Large";
pub const HTTP_URI_TOO_LONG: [12]HTTPStatusText = "URI Too Long";
pub const HTTP_UNSUPPORTED_MEDIA_TYPE: [22]HTTPStatusText = "Unsupported Media Type";
pub const HTTP_RANGE_NOT_SATISFIABLE: [21]HTTPStatusText = "Range Not Satisfiable";
pub const HTTP_EXPECTATION_FAILED: [18]HTTPStatusText = "Expectation Failed";
pub const HTTP_TEAPOT: [12]HTTPStatusText = "I'm a teapot";
pub const HTTP_MISDIRECTED_REQUEST: [19]HTTPStatusText = "Misdirected Request";
pub const HTTP_UNPROCESSABLE_CONTENT: [21]HTTPStatusText = "Unprocessable Content";
pub const HTTP_LOCKED: [6]HTTPStatusText = "Locked";
pub const HTTP_FAILED_DEPENDENCY: [17]HTTPStatusText = "Failed Dependency";
pub const HTTP_TOO_EARLY: [9]HTTPStatusText = "Too Early";
pub const HTTP_UPGRADE_REQUIRED: [16]HTTPStatusText = "Upgrade Required";
pub const HTTP_PRECONDITION_REQUIRED: [21]HTTPStatusText = "Precondition Required";
pub const HTTP_TOO_MANY_REQUESTS: [17]HTTPStatusText = "Too Many Requests";
pub const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: [31]HTTPStatusText = "Request Header Fields Too Large";
pub const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS: [29]HTTPStatusText = "Unavailable For Legal Reasons";
pub const HTTP_INTERNAL_SERVER_ERROR: [21]HTTPStatusText = "Internal Server Error";
pub const HTTP_NOT_IMPLEMENTED: [15]HTTPStatusText = "Not Implemented";
pub const HTTP_BAD_GATEWAY: [11]HTTPStatusText = "Bad Gateway";
pub const HTTP_SERVICE_UNAVAILABLE: [19]HTTPStatusText = "Service Unavailable";
pub const HTTP_GATEWAY_TIMEOUT: [15]HTTPStatusText = "Gateway Timeout";
pub const HTTP_VERSION_NOT_SUPPORTED: [26]HTTPStatusText = "HTTP Version Not Supported";
pub const HTTP_VARIANT_ALSO_NEGOTIATES: [23]HTTPStatusText = "Variant Also Negotiates";
pub const HTTP_INSUFFICENT_STORAGE: [20]HTTPStatusText = "Insufficient Storage";
pub const HTTP_LOOP_DETECTED: [15]HTTPStatusText = "Loop Detected";
pub const HTTP_NOT_EXTENDED: [12]HTTPStatusText = "Not Extended";
pub const HTTP_NETWORK_AUTHENTICATION_REQUIRED: [30]HTTPStatusText = "Network Authentication Required";

// Hypertext Transfer Protocol Status Code and Status Text Hash Map
pub fn status_codes_map(allocator: type) type {
    const http_status_codes: type = standard.AutoHashMap(HTTPStatusCode, HTTPStatusText).init(allocator);

    http_status_codes.put(HTTP_ONE_HUNDRED, HTTP_CONTINUE) catch return;
    http_status_codes.put(HTTP_ONE_HUNDRED_ONE, HTTP_SWITCHING_PROTOCOLS) catch return;
    http_status_codes.put(HTTP_ONE_HUNDRED_TWO, HTTP_PROCESSING) catch return;
    http_status_codes.put(HTTP_ONE_HUNDRED_THREE, HTTP_EARLY_HINTS) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED, HTTP_OK) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_ONE, HTTP_CREATED) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_TWO, HTTP_ACCEPTED) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_THREE, HTTP_NON_AUTHORITATIVE_INFORMATION) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_FOUR, HTTP_NO_CONTENT) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_FIVE, HTTP_RESET_CONTENT) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_SIX, HTTP_PARTIAL_CONTENT) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_SEVEN, HTTP_MULTI_STATUS) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_EIGHT, HTTP_ALREADY_REPORTED) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_TWENTY_SIX, HTTP_IM_USED) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED, HTTP_MULTIPLE_CHOICES) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_ONE, HTTP_MOVED_PERMANENTLY) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_TWO, HTTP_FOUND) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_THREE, HTTP_SEE_OTHER) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_FOUR, HTTP_NOT_MODIFIED) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_SEVEN, HTTP_TEMPORARY_REDIRECT) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_EIGHT, HTTP_PREMANENT_REDIRECT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED, HTTP_BAD_REQUEST) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_ONE, HTTP_UNAUTHORIZED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWO, HTTP_PAYMENT_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_THREE, HTTP_FORBIDDEN) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FOUR, HTTP_NOT_FOUND) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FIVE, HTTP_METHOD_NOT_ALLOWED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SIX, HTTP_NOT_ACCEPTABLE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SEVEN, HTTP_PROXY_AUTHENTICATION_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_EIGHT, HTTP_REQUEST_TIMEOUT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_NINE, HTTP_CONFLICT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TEN, HTTP_GONE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_ELEVEN, HTTP_LENGTH_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWELVE, HTTP_PRECONDITION_FAILED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_THIRTEEN, HTTP_CONTENT_TOO_LARGE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FOURTEEN, HTTP_URI_TOO_LONG) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FIFTEEN, HTTP_UNSUPPORTED_MEDIA_TYPE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SIXTEEN, HTTP_RANGE_NOT_SATISFIABLE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SEVENTEEN, HTTP_EXPECTATION_FAILED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_EIGHTEEN, HTTP_TEAPOT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_ONE, HTTP_MISDIRECTED_REQUEST) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_TWO, HTTP_UNPROCESSABLE_CONTENT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_THREE, HTTP_LOCKED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_FOUR, HTTP_FAILED_DEPENDENCY) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_FIVE, HTTP_TOO_EARLY) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_SIX, HTTP_UPGRADE_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_EIGHT, HTTP_PRECONDITION_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_NINE, HTTP_TOO_MANY_REQUESTS) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_THIRTY_ONE, HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FIFTEY_ONE, HTTP_UNAVAILABLE_FOR_LEGAL_REASONS) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED, HTTP_INTERNAL_SERVER_ERROR) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_ONE, HTTP_NOT_IMPLEMENTED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_TWO, HTTP_BAD_GATEWAY) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_THREE, HTTP_SERVICE_UNAVAILABLE) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_FOUR, HTTP_GATEWAY_TIMEOUT) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_FIVE, HTTP_VERSION_NOT_SUPPORTED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_SIX, HTTP_VARIANT_ALSO_NEGOTIATES) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_SEVEN, HTTP_INSUFFICENT_STORAGE) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_EIGHT, HTTP_LOOP_DETECTED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_TEN, HTTP_NOT_EXTENDED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_ELEVEN, HTTP_NETWORK_AUTHENTICATION_REQUIRED) catch return;

    return http_status_codes;
}
