const standard: type = @import("std");

// Hypertext Transfer Protocol Status Code Definition
pub const HttpStatusCode: type = []const u8;

// Hypertext Transfer Protocol Status Text Definition
pub const HttpStatusText: type = []const u8;

// Hypertext Transfer Protocol Status Codes
pub const HTTP_ONE_HUNDRED: [3]HttpStatusCode = "100";
pub const HTTP_ONE_HUNDRED_ONE: [3]HttpStatusCode = "101";
pub const HTTP_ONE_HUNDRED_TWO: [3]HttpStatusCode = "102";
pub const HTTP_ONE_HUNDRED_THREE: [3]HttpStatusCode = "103";
pub const HTTP_TWO_HUNDRED: [3]HttpStatusCode = "200";
pub const HTTP_TWO_HUNDRED_ONE: [3]HttpStatusCode = "201";
pub const HTTP_TWO_HUNDRED_TWO: [3]HttpStatusCode = "202";
pub const HTTP_TWO_HUNDRED_THREE: [3]HttpStatusCode = "203";
pub const HTTP_TWO_HUNDRED_FOUR: [3]HttpStatusCode = "204";
pub const HTTP_TWO_HUNDRED_FIVE: [3]HttpStatusCode = "205";
pub const HTTP_TWO_HUNDRED_SIX: [3]HttpStatusCode = "206";
pub const HTTP_TWO_HUNDRED_SEVEN: [3]HttpStatusCode = "207";
pub const HTTP_TWO_HUNDRED_EIGHT: [3]HttpStatusCode = "208";
pub const HTTP_TWO_HUNDRED_TWENTY_SIX: [3]HttpStatusCode = "226";
pub const HTTP_THREE_HUNDRED: [3]HttpStatusCode = "300";
pub const HTTP_THREE_HUNDRED_ONE: [3]HttpStatusCode = "301";
pub const HTTP_THREE_HUNDRED_TWO: [3]HttpStatusCode = "302";
pub const HTTP_THREE_HUNDRED_THREE: [3]HttpStatusCode = "303";
pub const HTTP_THREE_HUNDRED_FOUR: [3]HttpStatusCode = "304";
pub const HTTP_THREE_HUNDRED_SEVEN: [3]HttpStatusCode = "307";
pub const HTTP_THREE_HUNDRED_EIGHT: [3]HttpStatusCode = "308";
pub const HTTP_FOUR_HUNDRED: [3]HttpStatusCode = "400";
pub const HTTP_FOUR_HUNDRED_ONE: [3]HttpStatusCode = "401";
pub const HTTP_FOUR_HUNDRED_TWO: [3]HttpStatusCode = "402";
pub const HTTP_FOUR_HUNDRED_THREE: [3]HttpStatusCode = "403";
pub const HTTP_FOUR_HUNDRED_FOUR: [3]HttpStatusCode = "404";
pub const HTTP_FOUR_HUNDRED_FIVE: [3]HttpStatusCode = "405";
pub const HTTP_FOUR_HUNDRED_SIX: [3]HttpStatusCode = "406";
pub const HTTP_FOUR_HUNDRED_SEVEN: [3]HttpStatusCode = "407";
pub const HTTP_FOUR_HUNDRED_EIGHT: [3]HttpStatusCode = "408";
pub const HTTP_FOUR_HUNDRED_NINE: [3]HttpStatusCode = "409";
pub const HTTP_FOUR_HUNDRED_TEN: [3]HttpStatusCode = "410";
pub const HTTP_FOUR_HUNDRED_ELEVEN: [3]HttpStatusCode = "411";
pub const HTTP_FOUR_HUNDRED_TWELVE: [3]HttpStatusCode = "412";
pub const HTTP_FOUR_HUNDRED_THIRTEEN: [3]HttpStatusCode = "413";
pub const HTTP_FOUR_HUNDRED_FOURTEEN: [3]HttpStatusCode = "414";
pub const HTTP_FOUR_HUNDRED_FIFTEEN: [3]HttpStatusCode = "415";
pub const HTTP_FOUR_HUNDRED_SIXTEEN: [3]HttpStatusCode = "416";
pub const HTTP_FOUR_HUNDRED_SEVENTEEN: [3]HttpStatusCode = "417";
pub const HTTP_FOUR_HUNDRED_EIGHTEEN: [3]HttpStatusCode = "418";
pub const HTTP_FOUR_HUNDRED_TWENTY_ONE: [3]HttpStatusCode = "421";
pub const HTTP_FOUR_HUNDRED_TWENTY_TWO: [3]HttpStatusCode = "422";
pub const HTTP_FOUR_HUNDRED_TWENTY_THREE: [3]HttpStatusCode = "423";
pub const HTTP_FOUR_HUNDRED_TWENTY_FOUR: [3]HttpStatusCode = "424";
pub const HTTP_FOUR_HUNDRED_TWENTY_FIVE: [3]HttpStatusCode = "425";
pub const HTTP_FOUR_HUNDRED_TWENTY_SIX: [3]HttpStatusCode = "426";
pub const HTTP_FOUR_HUNDRED_TWENTY_EIGHT: [3]HttpStatusCode = "428";
pub const HTTP_FOUR_HUNDRED_TWENTY_NINE: [3]HttpStatusCode = "429";
pub const HTTP_FOUR_HUNDRED_THIRTY_ONE: [3]HttpStatusCode = "431";
pub const HTTP_FOUR_HUNDRED_FIFTEY_ONE: [3]HttpStatusCode = "451";
pub const HTTP_FIVE_HUNDRED: [3]HttpStatusCode = "500";
pub const HTTP_FIVE_HUNDRED_ONE: [3]HttpStatusCode = "501";
pub const HTTP_FIVE_HUNDRED_TWO: [3]HttpStatusCode = "502";
pub const HTTP_FIVE_HUNDRED_THREE: [3]HttpStatusCode = "503";
pub const HTTP_FIVE_HUNDRED_FOUR: [3]HttpStatusCode = "504";
pub const HTTP_FIVE_HUNDRED_FIVE: [3]HttpStatusCode = "505";
pub const HTTP_FIVE_HUNDRED_SIX: [3]HttpStatusCode = "506";
pub const HTTP_FIVE_HUNDRED_SEVEN: [3]HttpStatusCode = "507";
pub const HTTP_FIVE_HUNDRED_EIGHT: [3]HttpStatusCode = "508";
pub const HTTP_FIVE_HUNDRED_TEN: [3]HttpStatusCode = "510";
pub const HTTP_FIVE_HUNDRED_ELEVEN: [3]HttpStatusCode = "511";

// Hypertext Transfer Protocol Status Texts
pub const HTTP_CONTINUE: [8]HttpStatusText = "Continue";
pub const HTTP_SWITCHING_PROTOCOLS: [19]HttpStatusText = "Switching Protocols";
pub const HTTP_PROCESSING: [10]HttpStatusText = "Processing";
pub const HTTP_EARLY_HINTS: [11]HttpStatusText = "Early Hints";
pub const HTTP_OK: [2]HttpStatusText = "OK";
pub const HTTP_CREATED: [7]HttpStatusText = "Created";
pub const HTTP_ACCEPTED: [8]HttpStatusText = "Accepted";
pub const HTTP_NON_AUTHORITATIVE_INFORMATION: [29]HttpStatusText = "Non-Authoritative Information";
pub const HTTP_NO_CONTENT: [10]HttpStatusText = "No Content";
pub const HTTP_RESET_CONTENT: [13]HttpStatusText = "Reset Content";
pub const HTTP_PARTIAL_CONTENT: [15]HttpStatusText = "Partial Content";
pub const HTTP_MULTI_STATUS: [12]HttpStatusText = "Multi-Status";
pub const HTTP_ALREADY_REPORTED: [16]HttpStatusText = "Already Reported";
pub const HTTP_IM_USED: [7]HttpStatusText = "IM Used";
pub const HTTP_MULTIPLE_CHOICES: [16]HttpStatusText = "Multiple Choices";
pub const HTTP_MOVED_PERMANENTLY: [17]HttpStatusText = "Moved Permanently";
pub const HTTP_FOUND: [5]HttpStatusText = "Found";
pub const HTTP_SEE_OTHER: [9]HttpStatusText = "See Other";
pub const HTTP_NOT_MODIFIED: [12]HttpStatusText = "Not Modified";
pub const HTTP_TEMPORARY_REDIRECT: [18]HttpStatusText = "Temporary Redirect";
pub const HTTP_PREMANENT_REDIRECT: [18]HttpStatusText = "Permanent Redirect";
pub const HTTP_BAD_REQUEST: [11]HttpStatusText = "Bad Request";
pub const HTTP_UNAUTHORIZED: [12]HttpStatusText = "Unauthorized";
pub const HTTP_PAYMENT_REQUIRED: [16]HttpStatusText = "Payment Required";
pub const HTTP_FORBIDDEN: [9]HttpStatusText = "Forbidden";
pub const HTTP_NOT_FOUND: [9]HttpStatusText = "Not Found";
pub const HTTP_METHOD_NOT_ALLOWED: [18]HttpStatusText = "Method Not Allowed";
pub const HTTP_NOT_ACCEPTABLE: [14]HttpStatusText = "Not Acceptable";
pub const HTTP_PROXY_AUTHENTICATION_REQUIRED: [29]HttpStatusText = "Proxy Authentication Required";
pub const HTTP_REQUEST_TIMEOUT: [15]HttpStatusText = "Request Timeout";
pub const HTTP_CONFLICT: [8]HttpStatusText = "Conflict";
pub const HTTP_GONE: [4]HttpStatusText = "Gone";
pub const HTTP_LENGTH_REQUIRED: [15]HttpStatusText = "Length Required";
pub const HTTP_PRECONDITION_FAILED: [19]HttpStatusText = "Precondition Failed";
pub const HTTP_CONTENT_TOO_LARGE: [17]HttpStatusText = "Content Too Large";
pub const HTTP_URI_TOO_LONG: [12]HttpStatusText = "URI Too Long";
pub const HTTP_UNSUPPORTED_MEDIA_TYPE: [22]HttpStatusText = "Unsupported Media Type";
pub const HTTP_RANGE_NOT_SATISFIABLE: [21]HttpStatusText = "Range Not Satisfiable";
pub const HTTP_EXPECTATION_FAILED: [18]HttpStatusText = "Expectation Failed";
pub const HTTP_TEAPOT: [12]HttpStatusText = "I'm a teapot";
pub const HTTP_MISDIRECTED_REQUEST: [19]HttpStatusText = "Misdirected Request";
pub const HTTP_UNPROCESSABLE_CONTENT: [21]HttpStatusText = "Unprocessable Content";
pub const HTTP_LOCKED: [6]HttpStatusText = "Locked";
pub const HTTP_FAILED_DEPENDENCY: [17]HttpStatusText = "Failed Dependency";
pub const HTTP_TOO_EARLY: [9]HttpStatusText = "Too Early";
pub const HTTP_UPGRADE_REQUIRED: [16]HttpStatusText = "Upgrade Required";
pub const HTTP_PRECONDITION_REQUIRED: [21]HttpStatusText = "Precondition Required";
pub const HTTP_TOO_MANY_REQUESTS: [17]HttpStatusText = "Too Many Requests";
pub const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: [31]HttpStatusText = "Request Header Fields Too Large";
pub const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS: [29]HttpStatusText = "Unavailable For Legal Reasons";
pub const HTTP_INTERNAL_SERVER_ERROR: [21]HttpStatusText = "Internal Server Error";
pub const HTTP_NOT_IMPLEMENTED: [15]HttpStatusText = "Not Implemented";
pub const HTTP_BAD_GATEWAY: [11]HttpStatusText = "Bad Gateway";
pub const HTTP_SERVICE_UNAVAILABLE: [19]HttpStatusText = "Service Unavailable";
pub const HTTP_GATEWAY_TIMEOUT: [15]HttpStatusText = "Gateway Timeout";
pub const HTTP_VERSION_NOT_SUPPORTED: [26]HttpStatusText = "HTTP Version Not Supported";
pub const HTTP_VARIANT_ALSO_NEGOTIATES: [23]HttpStatusText = "Variant Also Negotiates";
pub const HTTP_INSUFFICENT_STORAGE: [20]HttpStatusText = "Insufficient Storage";
pub const HTTP_LOOP_DETECTED: [13]HttpStatusText = "Loop Detected";
pub const HTTP_NOT_EXTENDED: [12]HttpStatusText = "Not Extended";
pub const HTTP_NETWORK_AUTHENTICATION_REQUIRED: [31]HttpStatusText = "Network Authentication Required";

// Hypertext Transfer Protocol Status Code and Status Text Hash Map
pub fn status_codes_map(allocator: type) type {
    const status_codes: type = standard.AutoHashMap(HttpStatusCode, HttpStatusText).init(allocator);

    status_codes.put(HTTP_ONE_HUNDRED, HTTP_CONTINUE) catch return;
    status_codes.put(HTTP_ONE_HUNDRED_ONE, HTTP_SWITCHING_PROTOCOLS) catch return;
    status_codes.put(HTTP_ONE_HUNDRED_TWO, HTTP_PROCESSING) catch return;
    status_codes.put(HTTP_ONE_HUNDRED_THREE, HTTP_EARLY_HINTS) catch return;
    status_codes.put(HTTP_TWO_HUNDRED, HTTP_OK) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_ONE, HTTP_CREATED) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_TWO, HTTP_ACCEPTED) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_THREE, HTTP_NON_AUTHORITATIVE_INFORMATION) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_FOUR, HTTP_NO_CONTENT) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_FIVE, HTTP_RESET_CONTENT) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_SIX, HTTP_PARTIAL_CONTENT) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_SEVEN, HTTP_MULTI_STATUS) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_EIGHT, HTTP_ALREADY_REPORTED) catch return;
    status_codes.put(HTTP_TWO_HUNDRED_TWENTY_SIX, HTTP_IM_USED) catch return;
    status_codes.put(HTTP_THREE_HUNDRED, HTTP_MULTIPLE_CHOICES) catch return;
    status_codes.put(HTTP_THREE_HUNDRED_ONE, HTTP_MOVED_PERMANENTLY) catch return;
    status_codes.put(HTTP_THREE_HUNDRED_TWO, HTTP_FOUND) catch return;
    status_codes.put(HTTP_THREE_HUNDRED_THREE, HTTP_SEE_OTHER) catch return;
    status_codes.put(HTTP_THREE_HUNDRED_FOUR, HTTP_NOT_MODIFIED) catch return;
    status_codes.put(HTTP_THREE_HUNDRED_SEVEN, HTTP_TEMPORARY_REDIRECT) catch return;
    status_codes.put(HTTP_THREE_HUNDRED_EIGHT, HTTP_PREMANENT_REDIRECT) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED, HTTP_BAD_REQUEST) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_ONE, HTTP_UNAUTHORIZED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWO, HTTP_PAYMENT_REQUIRED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_THREE, HTTP_FORBIDDEN) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_FOUR, HTTP_NOT_FOUND) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_FIVE, HTTP_METHOD_NOT_ALLOWED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_SIX, HTTP_NOT_ACCEPTABLE) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_SEVEN, HTTP_PROXY_AUTHENTICATION_REQUIRED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_EIGHT, HTTP_REQUEST_TIMEOUT) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_NINE, HTTP_CONFLICT) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TEN, HTTP_GONE) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_ELEVEN, HTTP_LENGTH_REQUIRED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWELVE, HTTP_PRECONDITION_FAILED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_THIRTEEN, HTTP_CONTENT_TOO_LARGE) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_FOURTEEN, HTTP_URI_TOO_LONG) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_FIFTEEN, HTTP_UNSUPPORTED_MEDIA_TYPE) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_SIXTEEN, HTTP_RANGE_NOT_SATISFIABLE) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_SEVENTEEN, HTTP_EXPECTATION_FAILED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_EIGHTEEN, HTTP_TEAPOT) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_ONE, HTTP_MISDIRECTED_REQUEST) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_TWO, HTTP_UNPROCESSABLE_CONTENT) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_THREE, HTTP_LOCKED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_FOUR, HTTP_FAILED_DEPENDENCY) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_FIVE, HTTP_TOO_EARLY) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_SIX, HTTP_UPGRADE_REQUIRED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_EIGHT, HTTP_PRECONDITION_REQUIRED) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_NINE, HTTP_TOO_MANY_REQUESTS) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_THIRTY_ONE, HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE) catch return;
    status_codes.put(HTTP_FOUR_HUNDRED_FIFTEY_ONE, HTTP_UNAVAILABLE_FOR_LEGAL_REASONS) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED, HTTP_INTERNAL_SERVER_ERROR) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_ONE, HTTP_NOT_IMPLEMENTED) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_TWO, HTTP_BAD_GATEWAY) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_THREE, HTTP_SERVICE_UNAVAILABLE) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_FOUR, HTTP_GATEWAY_TIMEOUT) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_FIVE, HTTP_VERSION_NOT_SUPPORTED) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_SIX, HTTP_VARIANT_ALSO_NEGOTIATES) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_SEVEN, HTTP_INSUFFICENT_STORAGE) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_EIGHT, HTTP_LOOP_DETECTED) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_TEN, HTTP_NOT_EXTENDED) catch return;
    status_codes.put(HTTP_FIVE_HUNDRED_ELEVEN, HTTP_NETWORK_AUTHENTICATION_REQUIRED) catch return;

    return status_codes;
}
