const standard: type = @import("std");

// Hypertext Transfer Protocol Status Code Definition
pub const HTTPStatusCode: type = [4]u8;

// Hypertext Transfer Protocol Status Text Definition
pub const HTTPStatusText: type = []u8;

// Hypertext Transfer Protocol Status Codes
pub const HTTP_ONE_HUNDRED: HTTPStatusCode = "100";
pub const HTTP_ONE_HUNDRED_ONE: HTTPStatusCode = "101";
pub const HTTP_ONE_HUNDRED_TWO: HTTPStatusCode = "102";
pub const HTTP_ONE_HUNDRED_THREE: HTTPStatusCode = "103";
pub const HTTP_TWO_HUNDRED: HTTPStatusCode = "200";
pub const HTTP_TWO_HUNDRED_ONE: HTTPStatusCode = "201";
pub const HTTP_TWO_HUNDRED_TWO: HTTPStatusCode = "202";
pub const HTTP_TWO_HUNDRED_THREE: HTTPStatusCode = "203";
pub const HTTP_TWO_HUNDRED_FOUR: HTTPStatusCode = "204";
pub const HTTP_TWO_HUNDRED_FIVE: HTTPStatusCode = "205";
pub const HTTP_TWO_HUNDRED_SIX: HTTPStatusCode = "206";
pub const HTTP_TWO_HUNDRED_SEVEN: HTTPStatusCode = "207";
pub const HTTP_TWO_HUNDRED_EIGHT: HTTPStatusCode = "208";
pub const HTTP_TWO_HUNDRED_TWENTY_SIX: HTTPStatusCode = "226";
pub const HTTP_THREE_HUNDRED: HTTPStatusCode = "300";
pub const HTTP_THREE_HUNDRED_ONE: HTTPStatusCode = "301";
pub const HTTP_THREE_HUNDRED_TWO: HTTPStatusCode = "302";
pub const HTTP_THREE_HUNDRED_THREE: HTTPStatusCode = "303";
pub const HTTP_THREE_HUNDRED_FOUR: HTTPStatusCode = "304";
pub const HTTP_THREE_HUNDRED_SEVEN: HTTPStatusCode = "307";
pub const HTTP_THREE_HUNDRED_EIGHT: HTTPStatusCode = "308";
pub const HTTP_FOUR_HUNDRED: HTTPStatusCode = "400";
pub const HTTP_FOUR_HUNDRED_ONE: HTTPStatusCode = "401";
pub const HTTP_FOUR_HUNDRED_TWO: HTTPStatusCode = "402";
pub const HTTP_FOUR_HUNDRED_THREE: HTTPStatusCode = "403";
pub const HTTP_FOUR_HUNDRED_FOUR: HTTPStatusCode = "404";
pub const HTTP_FOUR_HUNDRED_FIVE: HTTPStatusCode = "405";
pub const HTTP_FOUR_HUNDRED_SIX: HTTPStatusCode = "406";
pub const HTTP_FOUR_HUNDRED_SEVEN: HTTPStatusCode = "407";
pub const HTTP_FOUR_HUNDRED_EIGHT: HTTPStatusCode = "408";
pub const HTTP_FOUR_HUNDRED_NINE: HTTPStatusCode = "409";
pub const HTTP_FOUR_HUNDRED_TEN: HTTPStatusCode = "410";
pub const HTTP_FOUR_HUNDRED_ELEVEN: HTTPStatusCode = "411";
pub const HTTP_FOUR_HUNDRED_TWELVE: HTTPStatusCode = "412";
pub const HTTP_FOUR_HUNDRED_THIRTEEN: HTTPStatusCode = "413";
pub const HTTP_FOUR_HUNDRED_FOURTEEN: HTTPStatusCode = "414";
pub const HTTP_FOUR_HUNDRED_FIFTEEN: HTTPStatusCode = "415";
pub const HTTP_FOUR_HUNDRED_SIXTEEN: HTTPStatusCode = "416";
pub const HTTP_FOUR_HUNDRED_SEVENTEEN: HTTPStatusCode = "417";
pub const HTTP_FOUR_HUNDRED_EIGHTEEN: HTTPStatusCode = "418";
pub const HTTP_FOUR_HUNDRED_TWENTY_ONE: HTTPStatusCode = "421";
pub const HTTP_FOUR_HUNDRED_TWENTY_TWO: HTTPStatusCode = "422";
pub const HTTP_FOUR_HUNDRED_TWENTY_THREE: HTTPStatusCode = "423";
pub const HTTP_FOUR_HUNDRED_TWENTY_FOUR: HTTPStatusCode = "424";
pub const HTTP_FOUR_HUNDRED_TWENTY_FIVE: HTTPStatusCode = "425";
pub const HTTP_FOUR_HUNDRED_TWENTY_SIX: HTTPStatusCode = "426";
pub const HTTP_FOUR_HUNDRED_TWENTY_EIGHT: HTTPStatusCode = "428";
pub const HTTP_FOUR_HUNDRED_TWENTY_NINE: HTTPStatusCode = "429";
pub const HTTP_FOUR_HUNDRED_THIRTY_ONE: HTTPStatusCode = "431";
pub const HTTP_FOUR_HUNDRED_FIFTEY_ONE: HTTPStatusCode = "451";
pub const HTTP_FIVE_HUNDRED: HTTPStatusCode = "500";
pub const HTTP_FIVE_HUNDRED_ONE: HTTPStatusCode = "501";
pub const HTTP_FIVE_HUNDRED_TWO: HTTPStatusCode = "502";
pub const HTTP_FIVE_HUNDRED_THREE: HTTPStatusCode = "503";
pub const HTTP_FIVE_HUNDRED_FOUR: HTTPStatusCode = "504";
pub const HTTP_FIVE_HUNDRED_FIVE: HTTPStatusCode = "505";
pub const HTTP_FIVE_HUNDRED_SIX: HTTPStatusCode = "506";
pub const HTTP_FIVE_HUNDRED_SEVEN: HTTPStatusCode = "507";
pub const HTTP_FIVE_HUNDRED_EIGHT: HTTPStatusCode = "508";
pub const HTTP_FIVE_HUNDRED_TEN: HTTPStatusCode = "510";
pub const HTTP_FIVE_HUNDRED_ELEVEN: HTTPStatusCode = "511";

// Hypertext Transfer Protocol Status Texts
pub const HTTP_CONTINUE: [10]HTTPStatusText = "Continue";
pub const HTTP_SWITCHING_PROTOCOLS: [20]HTTPStatusText = "Switching Protocols";
pub const HTTP_PROCESSING: [12]HTTPStatusText = "Processing";
pub const HTTP_EARLY_HINTS: [12]HTTPStatusText = "Early Hints";
pub const HTTP_OK: [4]HTTPStatusText = "OK";
pub const HTTP_CREATED: [8]HTTPStatusText = "Created";
pub const HTTP_ACCEPTED: [10]HTTPStatusText = "Accepted";
pub const HTTP_NON_AUTHORITATIVE_INFORMATION: [30]HTTPStatusText = "Non-Authoritative Information";
pub const HTTP_NO_CONTENT: [12]HTTPStatusText = "No Content";
pub const HTTP_RESET_CONTENT: [14]HTTPStatusText = "Reset Content";
pub const HTTP_PARTIAL_CONTENT: [16]HTTPStatusText = "Partial Content";
pub const HTTP_MULTI_STATUS: [14]HTTPStatusText = "Multi-Status";
pub const HTTP_ALREADY_REPORTED: [18]HTTPStatusText = "Already Reported";
pub const HTTP_IM_USED: [10]HTTPStatusText = "IM Used";
pub const HTTP_MULTIPLE_CHOICES: [18]HTTPStatusText = "Multiple Choices";
pub const HTTP_MOVED_PERMANENTLY: [18]HTTPStatusText = "Moved Permanently";
pub const HTTP_FOUND: [6]HTTPStatusText = "Found";
pub const HTTP_SEE_OTHER: [10]HTTPStatusText = "See Other";
pub const HTTP_NOT_MODIFIED: [14]HTTPStatusText = "Not Modified";
pub const HTTP_TEMPORARY_REDIRECT: [20]HTTPStatusText = "Temporary Redirect";
pub const HTTP_PREMANENT_REDIRECT: [20]HTTPStatusText = "Permanent Redirect";
pub const HTTP_BAD_REQUEST: [12]HTTPStatusText = "Bad Request";
pub const HTTP_UNAUTHORIZED: [14]HTTPStatusText = "Unauthorized";
pub const HTTP_PAYMENT_REQUIRED: [20]HTTPStatusText = "Payment Required";
pub const HTTP_FORBIDDEN: [10]HTTPStatusText = "Forbidden";
pub const HTTP_NOT_FOUND: [10]HTTPStatusText = "Not Found";
pub const HTTP_METHOD_NOT_ALLOWED: [20]HTTPStatusText = "Method Not Allowed";
pub const HTTP_NOT_ACCEPTABLE: [16]HTTPStatusText = "Not Acceptable";
pub const HTTP_PROXY_AUTHENTICATION_REQUIRED: [30]HTTPStatusText = "Proxy Authentication Required";
pub const HTTP_REQUEST_TIMEOUT: [16]HTTPStatusText = "Request Timeout";
pub const HTTP_CONFLICT: [10]HTTPStatusText = "Conflict";
pub const HTTP_GONE: [6]HTTPStatusText = "Gone";
pub const HTTP_LENGTH_REQUIRED: [16]HTTPStatusText = "Length Required";
pub const HTTP_PRECONDITION_FAILED: [20]HTTPStatusText = "Precondition Failed";
pub const HTTP_CONTENT_TOO_LARGE: [18]HTTPStatusText = "Content Too Large";
pub const HTTP_URI_TOO_LONG: [14]HTTPStatusText = "URI Too Long";
pub const HTTP_UNSUPPORTED_MEDIA_TYPE: [24]HTTPStatusText = "Unsupported Media Type";
pub const HTTP_RANGE_NOT_SATISFIABLE: [22]HTTPStatusText = "Range Not Satisfiable";
pub const HTTP_EXPECTATION_FAILED: [20]HTTPStatusText = "Expectation Failed";
pub const HTTP_TEAPOT: [14]HTTPStatusText = "I'm a teapot";
pub const HTTP_MISDIRECTED_REQUEST: [20]HTTPStatusText = "Misdirected Request";
pub const HTTP_UNPROCESSABLE_CONTENT: [22]HTTPStatusText = "Unprocessable Content";
pub const HTTP_LOCKED: [8]HTTPStatusText = "Locked";
pub const HTTP_FAILED_DEPENDENCY: [18]HTTPStatusText = "Failed Dependency";
pub const HTTP_TOO_EARLY: [10]HTTPStatusText = "Too Early";
pub const HTTP_UPGRADE_REQUIRED: [16]HTTPStatusText = "Upgrade Required";
pub const HTTP_PRECONDITION_REQUIRED: [22]HTTPStatusText = "Precondition Required";
pub const HTTP_TOO_MANY_REQUESTS: [18]HTTPStatusText = "Too Many Requests";
pub const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: [32]HTTPStatusText = "Request Header Fields Too Large";
pub const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS: [30]HTTPStatusText = "Unavailable For Legal Reasons";
pub const HTTP_INTERNAL_SERVER_ERROR: [22]HTTPStatusText = "Internal Server Error";
pub const HTTP_NOT_IMPLEMENTED: [16]HTTPStatusText = "Not Implemented";
pub const HTTP_BAD_GATEWAY: [12]HTTPStatusText = "Bad Gateway";
pub const HTTP_SERVICE_UNAVAILABLE: [20]HTTPStatusText = "Service Unavailable";
pub const HTTP_GATEWAY_TIMEOUT: [16]HTTPStatusText = "Gateway Timeout";
pub const HTTP_VERSION_NOT_SUPPORTED: [28]HTTPStatusText = "HTTP Version Not Supported";
pub const HTTP_VARIANT_ALSO_NEGOTIATES: [20]HTTPStatusText = "Variant Also Negotiates";
pub const HTTP_INSUFFICENT_STORAGE: [22]HTTPStatusText = "Insufficient Storage";
pub const HTTP_LOOP_DETECTED: [14]HTTPStatusText = "Loop Detected";
pub const HTTP_NOT_EXTENDED: [14]HTTPStatusText = "Not Extended";
pub const HTTP_NETWORK_AUTHENTICATION_REQUIRED: [32]HTTPStatusText = "Network Authentication Required";

// Hypertext Transfer Protocol Status Code and Status Text Hash Map
pub fn hypertext_transfer_status_codes(allocator: type) type {
    const http_status_codes: type = standard.AutoHashMap(HTTPStatusCode, HTTPStatusText).init(allocator);

    http_status_codes.put(HTTP_ONE_HUNDRED, HTTP_CONTINUE) catch return;
    http_status_codes.put(HTTP_ONE_HUNDRED_ONE, HTTP_SWITCHING_PROTOCOLS) catch return;
    http_status_codes.put(HTTP_ONE_HUNDRED_TWO, HTTP_PROCESSING) catch return;
    http_status_codes.put(HTTP_ONE_HUNDRED_THREE, HTTP_EARLY_HINTS) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED, HTTP_OK) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_ONE, HTTP_CREATED) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_TWO, HTTP_ACCEPTED) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_THREE, HTTP_NON_AUTHORITATIVE_INFORMATION) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_FOUR, HTTP_NO_CONTENT) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_FIVE, HTTP_RESET_CONTENT) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_SIX, HTTP_PARTIAL_CONTENT) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_SEVEN, HTTP_MULTI_STATUS) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_EIGHT, HTTP_ALREADY_REPORTED) catch return;
    http_status_codes.put(HTTP_TWO_HUNDRED_TWENTY_SIX, HTTP_IM_USED) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED, HTTP_MULTIPLE_CHOICES) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_ONE, HTTP_MOVED_PERMANENTLY) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_TWO, HTTP_FOUND) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_THREE, HTTP_SEE_OTHER) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_FOUR, HTTP_NOT_MODIFIED) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_SEVEN, HTTP_TEMPORARY_REDIRECT) catch return;
    http_status_codes.put(HTTP_THREE_HUNDRED_EIGHT, HTTP_PREMANENT_REDIRECT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED, HTTP_BAD_REQUEST) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_ONE, HTTP_UNAUTHORIZED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWO, HTTP_PAYMENT_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_THREE, HTTP_FORBIDDEN) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FOUR, HTTP_NOT_FOUND) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FIVE, HTTP_METHOD_NOT_ALLOWED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SIX, HTTP_NOT_ACCEPTABLE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SEVEN, HTTP_PROXY_AUTHENTICATION_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_EIGHT, HTTP_REQUEST_TIMEOUT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_NINE, HTTP_CONFLICT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TEN, HTTP_GONE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_ELEVEN, HTTP_LENGTH_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWELVE, HTTP_PRECONDITION_FAILED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_THIRTEEN, HTTP_CONTENT_TOO_LARGE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FOURTEEN, HTTP_URI_TOO_LONG) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FIFTEEN, HTTP_UNSUPPORTED_MEDIA_TYPE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SIXTEEN, HTTP_RANGE_NOT_SATISFIABLE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_SEVENTEEN, HTTP_EXPECTATION_FAILED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_EIGHTEEN, HTTP_TEAPOT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_ONE, HTTP_MISDIRECTED_REQUEST) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_TWO, HTTP_UNPROCESSABLE_CONTENT) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_THREE, HTTP_LOCKED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_FOUR, HTTP_FAILED_DEPENDENCY) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_FIVE, HTTP_TOO_EARLY) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_SIX, HTTP_UPGRADE_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_EIGHT, HTTP_PRECONDITION_REQUIRED) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_TWENTY_NINE, HTTP_TOO_MANY_REQUESTS) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_THIRTY_ONE, HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE) catch return;
    http_status_codes.put(HTTP_FOUR_HUNDRED_FIFTEY_ONE, HTTP_UNAVAILABLE_FOR_LEGAL_REASONS) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED, HTTP_INTERNAL_SERVER_ERROR) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_ONE, HTTP_NOT_IMPLEMENTED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_TWO, HTTP_BAD_GATEWAY) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_THREE, HTTP_SERVICE_UNAVAILABLE) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_FOUR, HTTP_GATEWAY_TIMEOUT) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_FIVE, HTTP_VERSION_NOT_SUPPORTED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_SIX, HTTP_VARIANT_ALSO_NEGOTIATES) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_SEVEN, HTTP_INSUFFICENT_STORAGE) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_EIGHT, HTTP_LOOP_DETECTED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_TEN, HTTP_NOT_EXTENDED) catch return;
    http_status_codes.put(HTTP_FIVE_HUNDRED_ELEVEN, HTTP_NETWORK_AUTHENTICATION_REQUIRED) catch return;

    return http_status_codes;
}
